### ISSUE TITLE
Modes that need to be merged

### ISSUE THREAD

**Issue by jojojames** [jojojames/evil-collection#10]
https://github.com/jojojames/evil-integrations/issues/1#issuecomment-341984606

    ansi-term / term
    help
    package-menu
    profiler

@Ambrevar I think I added the ones from my end, what's left are modes that probably won't go in (like org and the packages that would probably require some merging.)

Like a nice intermediary step is for me to push ^ those above packages and you can just modify it as you like after?

**Comment by Ambrevar** [comment]
> Like a nice intermediary step is for me to push ^ those above packages and you can just modify it as you like after?

What's the "^"?

Yes, add yours first, I'll to the merge and add the rest of my stuff tomorrow.

**Comment by jojojames** [comment]
^ was just those 4 modes in the list.

I've added what I needed to. You can do your thing @Ambrevar 🥇

**Comment by Ambrevar** [comment]
Note to myself: Add
- debbugs
- elfeed
- emms
- helm
- image+
- pdftools
- transmission
- ztree

**Comment by Ambrevar** [comment]
I've completed the merge.

I've kept my version of help, package-menu, and profiler since it uses hand-written bindings that are more consistent with the rationale.

Regarding term / ansi-term: I've renamed it to "term", I think it translates better that this targets all term-based modes.
I've integrate your idea of not going back when switching to normal mode.

**Comment by jojojames** [comment]
Awesome. We can close this one then.

**Comment by jojojames** [comment]
@Ambrevar For evil-term, not sure if you had mentioned this before, but the insert maps didn't seem to work for me.

C-a, C-b, tab, etc. I'll add back in the insert maps I had for the time being.

**Comment by Ambrevar** [comment]
Hmm, you shouldn't have.  I made sure this worked when I merged, but if it does not for you, then my test was flawed.  We should not need those keys anyways.  I'll work on a proper fix.

**Comment by Ambrevar** [comment]
You are right, it was broken, but I'm not sure I understand what's happening precisely.
In my case `C-f` and `C-b` would work as expected.  Can you confirm?

I'll see about it tomorrow.

**Comment by jojojames** [comment]
What do you expect those to do by the way?

I expect those C-* keys to work similar to a regular terminal in insert state.

I.e. C-b should move back a character in the terminal.

**Comment by Ambrevar** [comment]
Sorry, my phrasing was confusing.  Yes of course I'm expecting `C-*` keys to do what they ought: be passed to the underlying shell.
In most cases, your shell would understand these bindings Emacs-style.

In my case, `C-f` and `C-b` _do work properly_, while most other bindings don't, instead some unprintable character is inserted.  I'd like to understand why.

**Comment by Ambrevar** [comment]
OK, got it: Evil has some `C-` prefixed bindings in insert mode, that's why only some `C-` bindings were shadowed.  You are right, we need the override those keys, except for `C-c` and `C-h` I'd say.
I'll push a change as soon as possible.

**Comment by Ambrevar** [comment]
Fixed: 9c263e5.
