### ISSUE TITLE
Normalize the documentation header

### ISSUE THREAD

**Issue by Ambrevar** [jojojames/evil-collection#12]
Let's make it consistent. I like the following:
```
;;; evil-bookmarks.el --- Evil bindings for bookmarks. -*- lexical-binding: t -*-
```

Then
```
;; Author: James Nguyen <james@jojojames.com>
;; Maintainer: James Nguyen <james@jojojames.com>, Pierre Neidhardt <ambrevar@gmail.com>
```
I guess for now we can keep both our names as maintainers.
As for the author, first come first served.

- Does "emacs" makes sense as a keyword?  Isn't it obvious this is Emacs?

- Isn't URL and HomePage redundant?

**Comment by Ambrevar** [comment]
Can we leave the "Commentary" section empty when there is nothing special about that package?

**Comment by jojojames** [comment]
Agree with most of your suggestions. Commenting on the rest.

> Does "emacs" makes sense as a keyword? Isn't it obvious this is Emacs?

Yeah, we can remove it.

> Isn't URL and HomePage redundant?

Hmnn, I'm thinking we *might* need it. I'm not sure if melpa requires it or it was checkdoc or package-lint that wants it.

> Can we leave the "Commentary" section empty when there is nothing special about that package?

I need to double check if checkdoc/package-lint complains without it. I think it does IIRC.

**Comment by jojojames** [comment]
One nit;

> ;; Maintainer: James Nguyen <james@jojojames.com>, Pierre Neidhardt <ambrevar@gmail.com>

Maybe one name per line in a list to stay within a nice 80 character limit. :)

**Comment by Ambrevar** [comment]
> Maybe one name per line in a list to stay within a nice 80 character limit. :)

What's the syntax?

**Comment by jojojames** [comment]
Taken from magit.el.

;; Author: Marius Vollmer <marius.vollmer@gmail.com>
;; Maintainer: Jonas Bernoulli <jonas@bernoul.li>
;;	Kyle Meyer        <kyle@kyleam.com>
;;	Noam Postavsky    <npostavs@users.sourceforge.net>
;; Former-Maintainers:
;;	Nicolas Dudebout  <nicolas.dudebout@gatech.edu>
;;	Peter J. Weisberg <pj@irregularexpressions.net>
;;	Phil Jackson      <phil@shellarchive.co.uk>
;;	Rémi Vanicat      <vanicat@debian.org>
;;	Yann Hodique      <yann.hodique@gmail.com>

**Comment by Ambrevar** [comment]
package-lint:

> 10:1: warning: You should include standard keywords: see the variable `finder-known-keywords'.

**Comment by Ambrevar** [comment]
HomePage does not seem to be required neither by MELPA, checkdoc or package-lint.

**Comment by Ambrevar** [comment]
> > Can we leave the "Commentary" section empty when there is nothing special about that package?

> I need to double check if checkdoc/package-lint complains without it. I think it does IIRC.

It is not mandatory but recommended since it documents the package.  Let's use it only when relevant and in the entry point,  `evil-collection.el`.

I'll remove the rest.

**Comment by Ambrevar** [comment]
Also there should be no period at the end of the one-liner description.

**Comment by Ambrevar** [comment]
;; Package-Requires: ((evil "1.2.3"))

We should require `evil`.  But which version?
Emacs version requirement?

**Comment by Ambrevar** [comment]
Actually package-lint complains about empty "Commentaries sections".

**Comment by jojojames** [comment]
Yeah, I need to give it a run through myself at some point. I think if we want to kickstart into melpa quickly, we should take care of it sooner rather than later.

**Comment by Ambrevar** [comment]
I'll add a tag of the tasks we need to close before going on MELPA.

**Comment by jojojames** [comment]
Package-lint now gives no errors and the header is normalized. We can close this and account for new errors once they crop up.
