### ISSUE TITLE
Documentation: use "state", not "mode"

### ISSUE THREAD

**Issue by Ambrevar** [jojojames/evil-collection#13]
Evil uses "state" for normal, insert, motion, etc.
This is to avoid confusion with the term "mode" which has a completely different meaning in Emacs.

Let's review the comments and the documentation to make sure there is no confabulation between "state" and "mode".
Non-Evil bindings should be referred to as "Emacs state bindings".

**Comment by jojojames** [comment]
I took a skim myself and corrected a few places.

**Comment by jojojames** [comment]
Feel free to close this issue once you've had a chance to look @Ambrevar.

**Comment by Ambrevar** [comment]
The issue is an easy mistake that might pop up again, so I suggest we keep it around, at least until we go on MELPA.

**Comment by jojojames** [comment]
I'm going to close this now. Lets re-open create new issues if they crop up or mark it in the rationale.
