### ISSUE TITLE
Documentation: Review readme.org

### ISSUE THREAD

**Issue by Ambrevar** [jojojames/evil-collection#14]
At first glance, there is still a mention of "evil-special-modes".

**Comment by jojojames** [comment]
I will take a closer look later but one thing stands out.

> This is a collection of Evil bindings for the rest of Emacs that Evil does not cover by default

I think we may want to cover these too. evil-mode's integration is very barebones and in the future, it might be good to do a pull request to give the option to disable evil-mode's basic integration and use this package instead.

**Comment by Ambrevar** [comment]
OK.  Could you list some of the barebone modes?
One that comes to mind: nXML.

**Comment by jojojames** [comment]
They are all in evil-integration.el.

Here's some of them that just use the hjkl macro.

```
;;; Buffer-menu

(evil-add-hjkl-bindings Buffer-menu-mode-map 'motion)

;; dictionary.el

(evil-add-hjkl-bindings dictionary-mode-map 'motion
  "?" 'dictionary-help        ; "h"
  "C-o" 'dictionary-previous) ; "l"

;;; Dired

(eval-after-load 'dired
  '(progn
     ;; use the standard Dired bindings as a base
     (defvar dired-mode-map)
     (evil-make-overriding-map dired-mode-map 'normal)
     (evil-add-hjkl-bindings dired-mode-map 'normal
       "J" 'dired-goto-file                   ; "j"
       "K" 'dired-do-kill-lines               ; "k"
       "r" 'dired-do-redisplay                ; "l"
       ;; ":d", ":v", ":s", ":e"
       ";" (lookup-key dired-mode-map ":"))))
```

**Comment by jojojames** [comment]
I'm done with this as an issue. Lets rework the readme as issues arise.
