### ISSUE TITLE
autoload cookie

### ISSUE THREAD

**Issue by Ambrevar** [jojojames/evil-collection#15]
I think we should have only one autoload: `evil-collection-init`.
I'll remove the others.

**Comment by jojojames** [comment]
Sounds good, feel free to close this issue once you do it.

**Comment by jojojames** [comment]
Probably this one ;D

https://github.com/jojojames/evil-collection/commit/13e03e987178d65f34aef928cb98a908fc033021

**Comment by Ambrevar** [comment]
The autoload cookies of my modes are not gone yet.

**Comment by Ambrevar** [comment]
Fixed: 9d615fd677fc5dbdb5771c2314405fc328a13017.

**Comment by fbergroth** [comment]
@Ambrevar that commit also removed the cookie from `evil-collection-init`, which I guess wasn't intended?

**Comment by Ambrevar** [comment]
Indeed, strange I missed that.  Fixed: b256a69.
