### ISSUE TITLE
Rationale: Sorting vs. Filtering

### ISSUE THREAD

**Issue by Ambrevar** [jojojames/evil-collection#20]
Filtering (a.k.a. searching / narrowing) is an action that is common to many modes.
Sorting less so however.

It seems that many modes in Emacs state use "s" or "S" for sorting.
If we use the same in Evil states, then what key should we reserve for filtering?

Filtering bindings are inconsistent in Emacs state.  We should not override `/` unless the new binding completely supersedes the functionality of `evil-search-forward`.

**Comment by Ambrevar** [comment]
This was discussed with @Somelauw for https://github.com/Somelauw/evil-org-mode/pull/26,
and while horizontal movement is unnecessary in some modes (a tad arguable in org-agenda), I find it _essential_ in Dired and Ibuffer: at allows me to select / copy parts of file names, etc.

Regardless, filtering is such a common action that I believe it should only be bound one of the insertion keys (point 7 in the rationale).

**Comment by jojojames** [comment]
I don't really do sorting/filtering myself (probably because I can't remember the key).

Which other key/keys are available @Ambrevar?

@auwsmit I agree with @Ambrevar, 'f' and 'F' are important horizontal movement keys.

**Comment by Ambrevar** [comment]
For now I see two options (I could be missing something important):

1. "o" for filtering, "s" for sorting.
2. "s" for sorting, "o" for filtering.

"a", "r", "x", "c" are often used for other things in my experience.

"i" and "p" are more rarely used, but I can't find any mnemonic that would connect them to filtering / selecting / narrowing / sorting.

**Comment by noctuid** [comment]
Mutt also uses `o` for sorting (inspiration for ranger's choice). 

> I find it essential in Dired and Ibuffer: at allows me to select / copy parts of file names, etc.

I agree it's best not to override `f` as a default, but I personally always use it for filtering. Anything that uses an operator or visual state isn't affected. I've never wanted to copy something in the middle of a file, so I haven't come across this issue.

> "i" and "p" are more rarely used, but I can't find any mnemonic that would connect them to filtering / selecting / narrowing / sorting.

`i` is in filter at least. `r` could be  "reduce" if it was available. Maybe `p` for "prune"? `s` has some okay mnemonics ("search," "shorten," "slash," "scale down," etc.). I like "prune" personally.

> "a", "r", "x", "c" are often used for other things in my experience.

Out of curiosity, are these used for similar things?

**Comment by jojojames** [comment]
o for s[o]rting
i for f[i]ltering

?

**Comment by auwsmit** [comment]
>o for s[o]rting
>i for f[i]ltering

I like the consistency/mnemonic in using the first vowel of each like that

**Comment by Ambrevar** [comment]
Interesting, but I don't know if this would be a mnemomnic-reflex for the majority of the users.  I personally never made the connection.

`o` meant "order" to me :)

**Comment by jojojames** [comment]
I think pneumonics are nice but I'm not sure they are a requirement.

Do you have an issue with i for filtering and o for sorting @Ambrevar?

**Comment by Ambrevar** [comment]
Not really, but why would "i" be better than "s"?

In the end "i", "o" or "s" does not matter much, so I think the rationale should be guide by what is most prevalent.
If "i" is not used in any existing mode / program, maybe it's not such a good idea.

**Comment by jojojames** [comment]
s seems like it would be more useful for some other functionality. I could foresee a mode where searching/filtering/sorting are all there.

> It seems that many modes in Emacs state use "s" or "S" for sorting.

It's also used for searching, IIRC. Should we place much weight on a common key in Emacs state though? There are standard keys Emacs uses. Lets decide if it's most appropriate when translating towards Evil instead. If f[il]ter makes more sense ignoring Emacs' historical bindings, it might be the better choice in the long run.

**Comment by Somelauw** [comment]
In some modes insert-state makes sense and we need `i` for insertion. One of these modes is the customize buffer. You may want to check if this and other modes need both filtering and insertion.

I think modes in which insertion makes sense should at least leave `i` and `a` undefined.

**Comment by Ambrevar** [comment]
Agreed.

So, back to "o for sorting", "s for filtering"?

**Comment by jojojames** [comment]
@Ambrevar I believe the action item for 'i' is to see if there exists a mode where filtering would conflict with entering insert state.

Customize is one to check. I'm not sure if there are any others. If there are no conflicts, 'i' is still perfectly suitable.

's' still might have the same problem by the way, where a mode contains searching + filtering (which seems more likely than a mode needing filtering + inserting). These are things to check, of course.

**Comment by Ambrevar** [comment]
I'm not sure I understand your last comment: filtering and sorting are the same things, unless it is "textual search" which is bound to `/` anyways.

**Comment by jojojames** [comment]
I don't see filtering and sorting as the same thing (maybe Emacs does?).

Filtering to me is in this vein.

1
2
3
4

'Filter' all *evens* out.

Result
1
3

Sorting is in this vein.
1
3
4
2

Result:
1
2
3
4

**Comment by noctuid** [comment]
I think @Ambrevar meant to say filtering and searching.

**Comment by Ambrevar** [comment]
Yes, I meant filtering and searching, sorry for the confusion.

**Comment by jojojames** [comment]
If you feel more strongly about 's', lets go with that. If we find it a problem in the future, we'll just switch it up.
