### ISSUE TITLE
Consistency: helm, ivy

### ISSUE THREAD

**Issue by Ambrevar** [jojojames/evil-collection#25]
I guess it would make sense for those bindings to be consistent.
Spacemacs has done some work in the area.

**Comment by jojojames** [comment]
Hmnn, which keys do you think are inconsistent?

I'm a little wary here because:

1. I don't have any evil bindings set and ivy works fine for me.
2. Helm is known to be a fairly inconsistent experience relative to emacs.

If we're trying to make it consistent, Helm is the one that needs to 'give way'.

**Comment by Ambrevar** [comment]
I'm thinking the motion key in the Ivy minibuffer, etc.  For now Ivy only has ivy-occur bindings.

I do not know Ivy very well and it seems that you do not know Helm very well, so I guess we have some homework to do! :)

No problem with making Helm "give way" :)

**Comment by jojojames** [comment]
I used helm for a while until I settled on ivy and it definitely has a few different conventions to it. Ivy as a package is a lot more 'emacs'-like.

I'm not sure the ivy minibuffer needs evil keys (maybe it's just because I myself never use motion-related keys in the minibuffer).

**Comment by Ambrevar** [comment]
I suppose this would only make sense for people who use evil-minibuffer (like me! :p).

Let's keep this open for anyone to contribute.  Otherwise I'll take a look at it when I have time.

**Comment by Ambrevar** [comment]
I've overhauled helm: most (all?) issues are fixed, many Evil classic are added, and it just happens that it matches Ivy bindings quite well.

There is still a lot of work to do, but that'll come with time.
I believe this can be closed for now.
