### ISSUE TITLE
Request: company

### ISSUE THREAD

**Issue by Ambrevar** [jojojames/evil-collection#26]
Company is very popular, it should probably be a high priority.

I personally use Helm as completion menu so I have little need for company-specific bindings.

**Comment by jojojames** [comment]
I'm not sure if we need one. I thought the integration between the two already worked fine.

I'll doublecheck at some point but I think any company related mapping is going to be ina C-* or function key or something.

**Comment by Ambrevar** [comment]
That comment suggested there is a big need for it: https://www.reddit.com/r/emacs/comments/7brlns/need_opinions_could_it_be_worthwhile_to_switch_to/dplgygt/?utm_name=emacs

I have no clue to be honest.

**Comment by jojojames** [comment]
Probably two things,

1. There's probably a few commands you can call directly when in a company completion dialog/list.
We can probably add some bindings here.

2. Users coming from Vim might want a more YCMD-like experience. Company supports this but the ones that want it has to find the right configuration to reproduce this experience. I can extract out that configuration from my own company setup to reproduce YCMD's behavior more faithfully.

I think we should do [1] if there are those types of keybindings. Would [2] be interesting @Ambrevar?

**Comment by Ambrevar** [comment]
I've never used YCMD, so it's basically your could.  Maybe you could you draft something on a branch?

**Comment by noctuid** [comment]
> Users coming from Vim might want a more YCMD-like experience. Company supports this but the ones that want it has to find the right configuration to reproduce this experience

Have you seen [company-tng.el](https://github.com/company-mode/company-mode/pull/706)? It was added to make company completion more like YCM.

**Comment by jojojames** [comment]
@noctuid That's the one. It's not set up by default for company though so it might be nice to have the company bindings set it up.

This is what I use for company to play nice with yasnippet as well as complete similarly to YCMD.
It might be too opinionated for this package though. I could probably add something more generic to this package but I'd end up disabling the integration in favor of my own.

```
(defun +company-tng-configure-default ()
    "Applies the default configuration to enable `company-tng'."
    (add-to-list 'company-frontends 'company-tng-frontend)
    (defun +company-expand-yasnippet-or-return ()
      "Expand yas template or call RET normally."
      (interactive)
      (if (and company-active-map
               company-selection-changed
               (car company-candidates)
               (get-text-property 0 'yas-template (nth company-selection
                                                       company-candidates)))
          (call-interactively #'company-complete-selection)
        (when company-selection-changed
          (company-complete-selection))
        (let ((company-active-map))
          (call-interactively (key-binding (kbd "RET"))))))

    (setq company-frontends
          '(company-tng-frontend
            company-pseudo-tooltip-unless-just-one-frontend
            company-echo-metadata-frontend
            company-preview-frontend
            company-quickhelp-frontend))

    ;; https://github.com/company-mode/company-mode/pull/706
    (defun +company-preview-frontend (command)
      "`company-mode' frontend showing the selection as if it had been inserted."
      (pcase command
        (`pre-command (company-preview-hide))
        (`post-command
         (unless (and company-selection-changed
                      (memq 'company-tng-frontend company-frontends))
           (company-preview-show-at-point (point)
                                          (nth company-selection
                                               company-candidates))))
        (`hide (company-preview-hide))))
    (advice-add #'company-preview-frontend :override #'+company-preview-frontend)

    (let ((keymap company-active-map))
      (define-key keymap [return] '+company-expand-yasnippet-or-return)
      (define-key keymap (kbd "RET") '+company-expand-yasnippet-or-return)
      (define-key keymap "\C-n" 'company-select-next-if-tooltip-visible-or-complete-selection)
      (define-key keymap [tab] 'company-select-next-if-tooltip-visible-or-complete-selection)
      (define-key keymap (kbd "TAB") 'company-select-next-if-tooltip-visible-or-complete-selection)
      (define-key keymap [S-tab] 'company-select-previous)
      (define-key keymap [S-iso-lefttab] 'company-select-previous)
      (define-key keymap [(shift tab)] 'company-select-previous)
      (define-key keymap [backtab] 'company-select-previous)
      (define-key keymap "\C-p" 'company-select-previous)
      (define-key keymap [backtab] 'company-select-previous)
      (define-key keymap (kbd "S-TAB") 'company-select-previous)))
```

**Comment by jojojames** [comment]
Using the default company-tng setup is probably OK. We might want to think about how to customize different parts of an integration though.

If we add bindings for some functionality for company (like open documentation in a popup window), we might want to use that part but not the company-tng/YCMD configuration.

**Comment by jojojames** [comment]
Lets consider this request closed since there's *some* level of integration now. If someone has an idea on how to better integrate with company. They can do so through a pull request.

**Comment by Ambrevar** [comment]
Vim uses `C-n` and `C-p` to navigate completion menus.  I've added this to the rationale, although I've not implemented this in practice.

I suggest we should abide by this convention.  I also like having `C-j/C-k` as synonyms.

**Comment by jojojames** [comment]
Sure, Emacs uses C-n and C-p for those types of movements too.

**Comment by Ambrevar** [comment]
Actually Emacs also has `M-n` and `M-p` to browse completion history.  Not sure how that should relate to Vim's bindings.

**Comment by jojojames** [comment]
If you have opinions on that @Ambrevar, I'm all ears. I don't really navigate completion menus that often so this isn't a big concern for me. We can go with what you think is reasonable.
