### ISSUE TITLE
Rationale: Jump (go to definition) and display other-window

### ISSUE THREAD

**Issue by Ambrevar** [jojojames/evil-collection#27]
Several modes (occur, pdf, etc.) allow to jump in other window or to display in other window (that is, pop up buffer but don't move the cursor).

In many cases, `RET` should jump to definition, i.e. act just like ~gd~.

Then what about `S-RET` to jump in other window, and `M-RET` to display in other window?

Also `o` or `C-o` have been used in some places I believe.

**Comment by jojojames** [comment]
I like o and C-o when it's available.

S-RET/M-RET also works for me.

**Comment by Ambrevar** [comment]
Actually `C-o` is an important global binding for `evil-jump-backward`.  I don't think we should override it, just like `'` and `\``.

If not `C-o`, then what about `O`?

**Comment by jojojames** [comment]
Sure, sounds good.

**Comment by jojojames** [comment]
For the rationale, 'Jumping' and 'Go to Definition' are separate concepts.

> Existing bindings:

    mu4e has j in Emacs, J in Evil.
    C-o is possibly used for “display other window”.

mu4e is a good example. J makes perfect sense but gd doesn't. 

Any kind of jump should probably exist on 'J' and go to definition is 'gd'.

**Comment by Ambrevar** [comment]
Acknowledged.  What other "jumps" can you think of?

**Comment by jojojames** [comment]
I'll have to get back to you on that as I think it's a relatively common idiom but not many come to mind.

mu4e and notmuch at the very least.

**Comment by Ambrevar** [comment]
Evil also has its own jumps with `C-i` and `C-o`.
Maybe that could be re-used instead of `J`?

**Comment by Ambrevar** [comment]
Instead of "go to definition" which is too specific or inappropriate phrasing in some contexts, I suggest "follow".

Thus there are two binding sets we should add to the rationale: "following" and "jumping".

- "Following" follows / displays (possibly in other window) the thing at point.

- "Jumping" is unrelated to the thing at point.

**Comment by jojojames** [comment]
> Evil also has its own jumps with C-i and C-o.
Maybe that could be re-used instead of J?

Lets not do that, those 'jumps' from evil are named accordingly from VIM.

The 'J' style jumps are Emacs style jumps.

> Instead of "go to definition" which is too specific or inappropriate phrasing in some contexts, I suggest "follow".

I'd suggest we err on the side of 'go to definition'. We shouldn't forget Emacs is primarily used by programmers who know what 'go to definition' is naturally. The key convention is even bound to [g]o to [d]efinition. Also, I assume most modes using 'gd' are programming modes anyway where go to definition actually makes the most sense. 'follow' on the other hand seems to be more introduced jargon that doesn't match the majority of modes.

Thus there are two binding sets we should add to the rationale: "following" and "jumping".

>    "Following" follows / displays (possibly in other window) the thing at point.
Like above, I'd err on the side of not introducing new terms. I think it's extra confusing to do that.
As a compromise, if we really want to introduce 'follow', we should add it in the same list of terms that can be under the 'goto definition' umbrella.

e.g. GoToDefinition / Following

 >   "Jumping" is unrelated to the thing at point.

Clarification here, jumping can sometimes be related to the thing at point. For example, your cursor is on an item, and you press the 'jump' key, it can potentially open up a menu of things you can jump to related to thing at point.

**Comment by Ambrevar** [comment]
> The 'J' style jumps are Emacs style jumps.

Acknowledged.

> Clarification here, jumping can sometimes be related to the thing at point.

Any example?

As for the wording, I suggested replacing "go to definition" with "follow" so that we don't introduce new terms.
While "go to definition" makes total sense in programming modes, it does not really work for pdf-utils, dired, and many special modes where the followed item is not a definition but a file, a picture, a pdf page, etc.
Conversely, "follow" is dubious wording for programming modes.

Maybe we can find some better word?

On the other hand, we could also separate the two entirely:
- "go to definition" in programming modes, bound to `gd`.
- "follow" in special modes, bound to `RET`/`S-RET`.

It is true however that the two will never overlap and they share the concept of "going to / following", so it also makes sense to merge them into one concept.

**Comment by jojojames** [comment]
> Any example?

I'll have to get back to you. Hard to come up with examples off the top of my head. :) You'll just have to take my word for it for now.

> As for the wording, I suggested replacing "go to definition" with "follow" so that we don't introduce new terms.

But I think 'follow' *is* the new term, people should be familiar with 'go to definition'. (The xref equivalent is 'xref-find-definition'.)

> While "go to definition" makes total sense in programming modes, it does not really work for pdf-utils, dired, and many special modes where the followed item is not a definition but a file, a picture, a pdf page, etc.
Conversely, "follow" is dubious wording for programming modes.

Although that's true, follow actually doesn't make complete sense in those other modes either.

> On the other hand, we could also separate the two entirely:

I kind of feel lke this is a 'solution looking for a problem'. We're really only talking about naming for a term that will lend itself a a key ('gd') in this case. (And the naming in this is just 'meta' information, for our rationale.)

I'm really doubtful any user will actually ever get confused with a 'GoToDefinition' terminology in a special/non programming mode.

'Follow' (or replace this word with any other suggestion) however, introduces another a new term that isn't pneumonic *or* familiar.

**Comment by Ambrevar** [comment]
Agreed with the "meta" aspect of the issue, so let's not spend to much ink on this.

There is an actual binding issue however: `RET` and `S-RET` are not used in programming modes. `gd` is used to "go to definition".
In some special modes, we have `RET`, `S-RET` and optionally `o`/`O` to "go to thing at point", but we _don't_ have `gd`, which would be weird in this case.
In some other other modes, the difference between "go to definition" and "go to thing at point" can be ambiguous and both `gd` and `RET` feel right.

**Comment by jojojames** [comment]
I think in that case, (where gd is not present), we should bind both keys to the same command.

It's similar to the movement keys gj/c-j/]/etc.

Sometimes that mode, doesn't have enough commands to actually go all the way to a ] key. In that case, I think we should just bind it to whatever is reasonable.

**Comment by Ambrevar** [comment]
You mean have `gd` and `RET` everywhere when reasonable?

Fine by me.

What about `RET` for "go to definition" in programming modes?
It goes to next line by default, which is fairly useless in my opinion, but that would steer away from Vim defaults, so I'd say no.

If you agree with the last point, then I suggest the following:

- `gd`: "go to definition"
- `gD`: "go to definition in other window"
- `RET`: "go to definition" in non-programming modes
- `S-RET`: "go to definition in other window" in non-programming modes
- `M-RET`: "view definition in other window" in non-programming modes

In that case, no need to use `o`/`O`.

For the comment tag, should we use `;; goto`? I'm fine with it, but some modes like "man" use it for a different purpose.  I'm also fine with extending the definition in the rationale.

**Comment by jojojames** [comment]
> You mean have gd and RET everywhere when reasonable?

Yeah.

> What about RET for "go to definition" in programming modes?

As you mentioned, lets keep the vim default.

> If you agree with the last point, then I suggest the following:

    gd: "go to definition" <--- works
    gD: "go to definition in other window" <--- works

    RET: "go to definition" in non-programming modes
    S-RET: "go to definition in other window" in non-programming modes
    M-RET: "view definition in other window" in non-programming modes

For the 'meta', the RET keys don't have to be 'go to definition', they can just be 'open' (whatever keyword you want to use) in non-programming modes.

e.g. I think this is fine.

RET: 'Follow' in non-programming modes. (There's probably a more suitable name even for the 'RET' keys, like 'open').

I think gd and RET are separate concepts *but* if there's no alternative, it would be reasonable to add whatever was on RET to gd.

**Comment by Ambrevar** [comment]
Fixed by #42.
