### ISSUE TITLE
Evil equivalent for M-, (e.g. xref-pop-marker-stack)

### ISSUE THREAD

**Issue by jojojames** [jojojames/evil-collection#3]
https://github.com/jojojames/evil-integrations/issues/1#issuecomment-341961849

> (3) So M-, is xref-pop-marker-stack and it's available in Evil. M-. is xref-find-definitions which is available in insert state, but in normal state, it's evil-repeat-pop-next.
Either way, this is an Evil's problem, I don't think it belongs to us to solve this.
This is how gd is used in my current bindings:

	evil-calendar.el:65:    "gd" 'calendar-goto-date ; "gd" in evil-org-agenda, "gd" in Emacs.
	evil-info.el:53:    "gd" 'Info-goto-node
	evil-man.el:47:    "gd" 'Man-goto-section
	evil-profiler.el:57:    "gd" 'profiler-report-find-entry

> In those cases, the xref commands don't apply, so there is no problem. '' or C-o will do what you want.

I think we want a keybind to represent a pop from definition if we're going to use gd for go to definition. If some modes don't have a need for a pop definition, that's fine, but we'd still need one for modes that use it (almost all the programming modes). I don't think " or C-o suffices because they fulfill a different use case.

A quick scenario where you'd need a pop definition key is.
1. Go To Definition on symbol
2. Use a jump of some kind (G gg or something else)

" or C-o will go to the last location you were
M-, (Emacs) would bring you to the place where you called Go To Definition

Re: Evil

Yes, I think Evil should have an option to not override M-..

**Comment by jojojames** [comment]
@Ambrevar I believe the Vim equivalent is C-t.
```
C-t runs the command pop-tag-mark (found in evil-normal-state-map),
which is an alias for ‘xref-pop-marker-stack’ in ‘etags.el’.

It is bound to C-t.

(pop-tag-mark)

Pop back to where M-x xref-find-definitions was last invoked.
```

http://vim.wikia.com/wiki/Browsing_programs_with_tags

If there's an available 'pop', we should use C-t.

**Comment by Ambrevar** [comment]
Acknowledged, but can you think of any mode that has a dedicated function for popping back?

**Comment by jojojames** [comment]
Yes, almost all the programming related modes.

**Comment by Ambrevar** [comment]
OK.
