### ISSUE TITLE
Melpa

### ISSUE THREAD

**Issue by jojojames** [jojojames/evil-collection#31]
@Ambrevar Lets try and move forward with Melpa so that it's easier to obtain evil-collection.

Here's a list of issues tagged with Melpa already. I am splitting it up by what I don't see as required and what is probably required.

**Required**
Normalize the documentation header - https://github.com/jojojames/evil-collection/issues/12
Documentation: use "state", not "mode" - https://github.com/jojojames/evil-collection/issues/13
Documentation: Review readme.org - https://github.com/jojojames/evil-collection/issues/14
Customizable initial/primary state - https://github.com/jojojames/evil-collection/issues/21

**Not Required**
Keybinding Syntax - https://github.com/jojojames/evil-collection/issues/8
Rationale: Sorting vs. Filtering - https://github.com/jojojames/evil-collection/issues/20
image-mode and pdf-tools conflict - https://github.com/jojojames/evil-collection/issues/23
Rationale: Marking - https://github.com/jojojames/evil-collection/issues/19

Some of the required are already done and are left as a reminder. The biggest one seems to be #21.

In not required, I don't want rationale discussions to block pushing to melpa and image-mode/pdf-mode also doesn't seem to be *too* important to block.

#8, keybinding syntax, I see it the same way I see evilify macro. We want to move in one direction but the current stuff is fine as it is too, so it shouldn't be a blocker.

Let me know if you disagree with any points. I'm trying to avoid spinning wheels here and leaving this repo "melpa-less" for months. I know quite a few people that don't like to vendor / use git submodules and would prefer going through the package archives.

**Comment by fbergroth** [comment]
Not sure if it will be an issue, or the proper way to solve it, but the packages which contains bindings to a third party library will fail to byte compile.

**Comment by jojojames** [comment]
Probably due to the require statements. We might have to require with no errors.

**Comment by fbergroth** [comment]
You could do that, but then you'd end up with warnings unless you forward declare variables.

**Comment by jojojames** [comment]
@fbergroth Which files do you think are problems?

Most files are just using function symbols (not variables) so I don't see a problem byte compiling them with the optional package require.

Try removing ag package for example and doing an optional require on it. It should byte compile fine.

I think, for the general case, that approach should work fine. Of course, if someone else had a better idea, we can go with that.

**Comment by fbergroth** [comment]
I tested with vlf, and when I changed `(require 'vlf nil t)` I got this warning: 

```
In evil-vlf-setup:
evil-vlf.el:36:4:Warning: reference to free variable ‘vlf-mode-map’
```

Which can be silenced by forward declaring it.

I'm not sure why I'm not getting the same warning with ag though.

**Comment by fbergroth** [comment]
Have a look at the output of #32

**Comment by fbergroth** [comment]
With compilation warnings out of the way, there are some issues reported by package-lint. I fixed a couple in #35.

What remains is:
- bad naming in `evil-collection-util.el` and `evil-evilified-state.el`
- `package-lint` crashes in `evil-pdf`, on the line with `(kbd "C-c <tab>")` - but that's an issue with `package-lint`

**Comment by jojojames** [comment]
@fbergroth I've made some changes for those. Package-lint should be good now.

**Comment by jojojames** [comment]
https://github.com/melpa/melpa/pull/5124

**Comment by Ambrevar** [comment]
Sorry for coming too late to the party, but I'd like to close one issue before release: stabilize the rationale, i.e. all "Rationale:" items.
I think it's important for the end users that our default keybindings do not change over time, or at least as little as possible.

I don't think it's so hard: I'll review the issues in depth in the coming days and make sure there is no conflict and everything is consistent.  If we all agree with the result, then let's go MELPA.

What do you think?

**Comment by jojojames** [comment]
I want to keep the rationale more flexible. If we pour cement all over it right now, that would be unfortunate.

I'd rather we take a "we're releasing this package but it's still subject to change" approach. As this project matures, a lot of the patterns will harden naturally.

Also, it's already submitted to Melpa and awaiting approval.

**Comment by Ambrevar** [comment]
OK, we can go for "flexible".
I suggest we have a last thorough round check for consistency though: if the bindings happen to be a mess and inconsistent with the rationale, the package would gather poor reputation.

**Comment by jojojames** [comment]
We should just put big red warnings up top that the keybindings are still in a state of flux. (This would have to go in the commentary section of evil-collection.el so MELPA users can see the note.)

**Comment by jojojames** [comment]
@Ambrevar 

As @purcell mentioned, we should prefix our sub-packages with 'evil-collection-'.

https://github.com/melpa/melpa/pull/5124

I'll get to that at some point but if you had time and got to it before me, that'd be awesome too.

**Comment by Ambrevar** [comment]
@jojojames I can do the change now, i.e. prefix everything with `evil-collection-`.
I'll be waiting for your confirmation after the last comments on the MELPA thread.

**Comment by jojojames** [comment]
@Ambrevar I like @purcell's suggestion.

evilcol- ?

The package can still be evil-collection, but the namespacing inside can be shortened a little.

I'll leave it up to you though when you make the change. (evil-collection-) is fine too.

**Comment by Ambrevar** [comment]
One last question before I apply the changes: should I rename all the files, the provides and the setup in `evil-collection.el` (which will be renamed to `evilcol.el`)?

That will break everyone's config.

**Comment by jojojames** [comment]
Yeah.

**Comment by jojojames** [comment]
@Ambrevar Let me know if you want me to make the change. Should be fairly quick. :)

**Comment by Ambrevar** [comment]
Sorry, I cannot commit much now I'm afraid.  If you can do it, you should go ahead :)
Don't forget to update the readme and the header comments in evil-collection.el.

**Comment by jojojames** [comment]
Thanks. No worries. I'll go ahead and get to it at some point.

**Comment by jojojames** [comment]
Gave it best efforts to update the namespace. Lets fix things as we find them.

I ended up with evil-collection as looking at evilcol- was a little weird after I made the change. We get the added benefit of not breaking anybody's config for the simple case where they just call the init function.

**Comment by Ambrevar** [comment]
Good job, thank you for going through this!

There are a few issues with modes defining custom functions like in Eshell and EMMS.  I'm working on it.

**Comment by jojojames** [comment]
Yeah, not surprised I broke a few things. :)

**Comment by Ambrevar** [comment]
Everything looks good on my end now.

**Comment by purcell** [comment]
Merged into MELPA now - thanks! :-)

**Comment by jojojames** [comment]
Thanks again @purcell !

**Comment by Ambrevar** [comment]
Thanks @purcell!

I just posted an [announcement on reddit](https://www.reddit.com/r/emacs/comments/7loyln/evil_collection_has_hit_melpa_enjoy_the_full_vim/).
