### ISSUE TITLE
Clean up byte-compiler's warnings

### ISSUE THREAD

**Issue by Ambrevar** [jojojames/evil-collection#37]
Following up on #22.

We want to have clean code and clean byte-compilation, i.e. no warnings.

As of now, some `defun`s are wrapped in `with-no-warnings` blocks.  This has several downsides:

- It silences possible valuable warnings inside the `defun`s.

- The warnings are spurious: we should not add kludges around correct code.  Code quality is more important than the opinion of an automated linter.

- It's not pretty and `defun`s are not top-level anymore.

**Comment by Ambrevar** [comment]
@fbergroth:

> @Ambrevar with that reasoning, evil-collection shouldn't require with noerror as well. This all is a hack to release this as a single package without declaring a dependency on every third party package.

Isn't there a proper way of doing this?  I'm no MELPA expert I'm afraid.

That being said, the `(require x nil t)` is a hack solving a different problem: dependencies.  This is much more important than some warnings.

Of course if we can remove warnings I'm all for it, but I don't think `with-no-errors` is the way to go.

**Comment by fbergroth** [comment]
The proper way would be to release a separate melpa package for every third party package we provide bindings for. Which is obviously too inconvenient, so we work around it.

I'm aware of the downsides you list, but I don't think there's any pretty solution at hand here. Either wrap all the stuff, or add kludge at every call site. The first having less noisy code, but less help from the byte compiler.

**Comment by Ambrevar** [comment]
What about leaving the warnings? I know it's an item on MELPA's checklist, but if the warnings are more reasonable than an unreliable kludge that could lead to broken code, the MELPA's team will understand (or come up with a better suggestion).

**Comment by fbergroth** [comment]
It's not just the melpa maintainers, I think as a user, you'll be put off by a package if it generates *some* warnings during installation. Before I sent a couple of PRs to this repo, I got a wall of warnings when compiling these files.

If someone knows a different trick, ofcourse that'd be good.

**Comment by jojojames** [comment]
I agree, and I think we should strive for no warnings too.

Is fboundp a good middleground @fbergroth and @Ambrevar?

BTW, my current stance on it is that I'm fine with the ignore-errors wrapping. I do see @Ambrevar concerns though. At the same time, this package should be simple enough (setting some bindings...) that it doesn't seem to be a huge deal to me.

**Comment by Ambrevar** [comment]
`fboundp` might look weird but at least it does not conceal positive warnings, so for now I'd rather go for that solution.

True that this package is simple enough, but the ignore-warnings wrapping is around functions, not just bindings.  While those functions are simple enough now, some future addition could be complex enough to need a good warning indicator.

**Comment by Ambrevar** [comment]
Should I move on to using `fboundp` then?

**Comment by jojojames** [comment]
Yeah.

**Comment by noctuid** [comment]
Shouldn't `declare-function` be used, or is there something else causing warnings?

**Comment by Ambrevar** [comment]
Agreed, `declare-function` is actually the proper way to deal with this issue.

That being said, I just ran `make lint` without the `with-no-warnings` blocks and it did not report anything.  Not sure what raised the issue in the first place.  I've remove the blocks for now.

**Comment by fbergroth** [comment]
Sigh. Try compiling it.

**Comment by fbergroth** [comment]
@noctuid `declare-function` won't solve byte-compilation.

**Comment by Ambrevar** [comment]
Sorry, I did `M-x emacs-lisp-byte-compile` and did not see any error.  Compiling from commandline throws error though, you are right.  Do you know why?

Also `declare-function` _does_ solve the issue for me (no error on `make`).

**Comment by fbergroth** [comment]
`make compile` compiles it with `emacs -Q`, so you probably have it installed locally.

Oh wow, I typo'd a quote when I was trying to use `declare-function`. Let's go for that then.

**Comment by Ambrevar** [comment]
Makes perfect sense.  Problem solved.
