### ISSUE TITLE
Remove package-lint workaround on C-c <tab>

### ISSUE THREAD

**Issue by Ambrevar** [jojojames/evil-collection#38]
Use conventional syntax for `C-c <tab>` once https://github.com/purcell/package-lint/issues/96 is resolved.

**Comment by jojojames** [comment]
Not about this topic specifically, but I'm curious about creating a new issue tracking *another* upstream issue for each upstream issue. One or two is probably fine but if these keep coming up, it'll be especially tricky to follow.

Would the TODO living in code be insufficient?

**Comment by Ambrevar** [comment]
You are absolutely right, I just opened this issue in a hurry, but we should use TODO items.

**Comment by purcell** [comment]
This is fixed in `package-lint` now - sorry for the hassle!

**Comment by Ambrevar** [comment]
Thank you!

**Comment by jojojames** [comment]
Did you run make lint @Ambrevar?
