### ISSUE TITLE
Error with emms

### ISSUE THREAD

**Issue by ericsfraga** [jojojames/evil-collection#39]
Hello,

I have just tried using evil-collection, with everything enabled, and get the following error backtrace when trying to start emacs:

`Debugger entered--Lisp error: (void-variable emms-browser-mode-map)
  (list emms-browser-mode-map emms-playlist-mode-map)
  (let ((--dolist-tail-- (list emms-browser-mode-map emms-playlist-mode-map))) (while --dolist-tail-- (let ((map (car --dolist-tail--))) (evil-define-key* 'motion map "+" 'emms-volume-raise "=" 'emms-volume-raise "-" 'emms-volume-lower "u" 'emms-playlist-mode-undo) (setq --dolist-tail-- (cdr --dolist-tail--)))))
  evil-emms-setup()
  funcall(evil-emms-setup)
  (closure ((req . emms) (--dolist-tail--) (reqs emms) (m . emms) (mode . emms) (--dolist-tail--) t) nil (require (intern (concat "evil-" (symbol-name m)))) (funcall (intern (concat "evil-" (symbol-name m) "-setup"))))()
  eval-after-load-helper("/home/ucecesf/synced/emacs/emms-4.2/lisp/emms.el")
  run-hook-with-args(eval-after-load-helper "/home/ucecesf/synced/emacs/emms-4.2/lisp/emms.el")
  do-after-load-evaluation("/home/ucecesf/synced/emacs/emms-4.2/lisp/emms.el")
  load-with-code-conversion("/home/ucecesf/synced/emacs/emms-4.2/lisp/emms.el" "/home/ucecesf/synced/emacs/emms-4.2/lisp/emms.el" nil t)
  require(emms)
  eval-buffer(#<buffer  *load*-332336> nil "/home/ucecesf/synced/emacs/emms-4.2/lisp/emms-browser.el" nil t)  ; Reading at buffer position 10941
  load-with-code-conversion("/home/ucecesf/synced/emacs/emms-4.2/lisp/emms-browser.el" "/home/ucecesf/synced/emacs/emms-4.2/lisp/emms-browser.el" nil t)
  require(emms-browser)`

In my experience, emms frequently causes difficulties unfortunately.

I am using emacs snapshot for Debian, v27.0.50.

**Comment by jojojames** [comment]
Hmnn, probably needs to be inside with-eval-after-load.

I don't use emms, so I'm just guessing.

https://github.com/jojojames/evil-collection/commit/58b9367f2955a9b8f7668eb7f3dc9dd56206de7e

Added a commit here. Hopefully that fixes it for you. @Ambrevar feel free to fix it up if it doesn't look right on your end.

**Comment by ericsfraga** [comment]
Thanks.  This fixes it!

**Comment by jojojames** [comment]
Thanks, it'll probably be a good idea to add some tests to validate some of these first run type situations.

**Comment by Ambrevar** [comment]
This is an upstream issue.  Since I'm going to take part into EMMS development, I'll see how we can fix this. 

Let's leave the `;; TODO` tag as a remainder.  Once the issue is fixed, we can safely remove the `with-eval-after-load` macros.
