### ISSUE TITLE
Key for refresh/redisplay (C-l/gr/etc)

### ISSUE THREAD

**Issue by jojojames** [jojojames/evil-collection#4]
https://github.com/jojojames/evil-integrations/issues/1#issuecomment-341961849

> (5) While C-l makes sense for refresh/redisplay because of terminals, I don't know if refreshing/redisplaying should be bound such a short binding, it's not something we always want to do, is it?
For now we have gr. r is used for other things.
It's a good suggestion though, I will include it to the rationale.

gr works for me and seems fairly standard among the other evil packages.

**Comment by jojojames** [comment]
@Ambrevar Did you have anything to add here? Otherwise we can close.

**Comment by Ambrevar** [comment]
According to https://github.com/Ambrevar/evil-special-modes/issues/1, `gr` is not exactly "standard", it's more of a new thing.

Question:
- `gr` or `C-l`?
- What about both?

My opinion: `gr` and leave `C-l` free.

**Comment by jojojames** [comment]
Yeah, fairly standard relative to evil packages.

gr works fine for me. That's what I use anyhow.

**Comment by Ambrevar** [comment]
Let's stick to `gr` then.
