### ISSUE TITLE
Rationale: g? for Help?

### ISSUE THREAD

**Issue by jojojames** [jojojames/evil-collection#40]
Would it make sense to just push the help keys (whatever would land on '?' normally) to 'g?'?

That way there's a guarantee '?' never gets replaced (which I'd suggest is almost always useful).

**Comment by Ambrevar** [comment]
I agree `?` is almost always useful. `g?` is however as long as `C-h m` to type, so I'm not sure there is a benefit.  Anything similar on the Vim side?  Otherwise why not leaving it to `C-h m` altogether, that would be one binding less to care about.
Keeping the rationale simple would also be a neat goal.

**Comment by jojojames** [comment]
I was thinking more about mode-specific help keys. I know quite a few modes (not off the top of my head :)) that have a separate help command.

A quick one is something like -> notmuch-help.

**Comment by Ambrevar** [comment]
What's the binding for `notmuch-help`?

**Comment by jojojames** [comment]
'?'

**Comment by Ambrevar** [comment]
OK for `g?` then.

**Comment by Ambrevar** [comment]
What about `K`? It's bound to `evil-lookup` by default and quite a few bindings you wrote use it.

**Comment by jojojames** [comment]
'K" is more for 'lookup' or 'lookup for symbol at point' or 'documentation for symbol at point'.

It usually has context attached to it.

'?' is more like 'here's the tutorial or help for this mode'!

**Comment by Ambrevar** [comment]
Yes, I'm not a big fan of using `K` either.  The nice thing though is that it is usually available in special modes.

**Comment by jojojames** [comment]
They are very separate concepts though.

Is there a problem with 'g?' that we are looking for alternatives?

**Comment by Somelauw** [comment]
I like `g?`. On the other hand, the following packages are already using `?`:
- https://github.com/emacs-evil/evil-magit#to-add-other-common-evil-commands
- https://github.com/emacs-evil/evil-ediff/blob/master/evil-ediff.el
- not-much apparently

An exception is https://github.com/JorisE/evil-mu4e/blob/master/evil-mu4e.el which uses `H` for help and binds `?` to `mu4e-headers-mark-for-unread`.

Can this key perhaps be made customizable using something like `general-translate-keys`?

**Comment by jojojames** [comment]
@Somelauw For notmuch, that's what the emacs' version of the binding uses. If we get a evil-notmuch version, I'd assume it'd go to 'g?' too.

Re: other modes,
'?' is a really good key and I wish they made the decision to go with 'g?' also.

Not sure what the possibilities are with general yet. I would like to try general-translate-keys or have it make it here at some point. @noctuid

**Comment by Ambrevar** [comment]
Like other bindings already, we can have `g?` everywhere for consistency and `?` in places where backward search is not very useful.

**Comment by jojojames** [comment]
Moved most (all?) the ? related commands to g? and updated the rationale.

https://github.com/jojojames/evil-collection/commit/de887fb4be12d84561b50b126449fd97c6df428b
