### ISSUE TITLE
Dired: handle dired-x

### ISSUE THREAD

**Issue by fbergroth** [jojojames/evil-collection#44]
When you `(require 'dired-x)`, a bunch of bindings is done on `dired-mode-map`.

These are bound based on `dired-bind-{man,info}`, which happens by default.
```
(define-key dired-mode-map "N" 'dired-man)
(define-key dired-mode-map "I" 'dired-info)
```

The following bindings are ran unconditionally:
```
(define-key dired-mode-map "\C-x\M-o" 'dired-omit-mode)
(define-key dired-mode-map "*O" 'dired-mark-omitted)
(define-key dired-mode-map "\M-(" 'dired-mark-sexp)
(define-key dired-mode-map "*(" 'dired-mark-sexp)
(define-key dired-mode-map "*." 'dired-mark-extension)
(define-key dired-mode-map "\M-!" 'dired-smart-shell-command)
(define-key dired-mode-map "\M-G" 'dired-goto-subdir)
(define-key dired-mode-map "F" 'dired-do-find-marked-files)
(define-key dired-mode-map "Y"  'dired-do-relsymlink)
(define-key dired-mode-map "%Y" 'dired-do-relsymlink-regexp)
(define-key dired-mode-map "V" 'dired-do-run-mail)
```

**Comment by Ambrevar** [comment]
Good catch.  The simple answer to this is to set some (all?) bindings in a `(with-eval-after-load 'dired-x` block.

I'm not a big dired user. @fbergroth, @jojojames, do you have suggestions for bindings?

**Comment by Ambrevar** [comment]
Even simpler: in evil-collection, setup dired with `(dired dired dired-x)`.

**Comment by jojojames** [comment]
We should really come up with a good set of bindings for dired. The bindings as of now are probably just to get it going.

I have a second set of local bindings set in my configuration to make it more evil. I'll try to merge the two at some point but it'd also be good to decide what goes where.

**Comment by fbergroth** [comment]
I think it makes sense to merge `dired-x` stuff into `evil-dired`. If you don't require `dired-x` explicitly, chances are high it'll get loaded anyway via some autoloaded function, such as `dired-jump`. If you go for `(dired dired dired-x)`, then `evil-dired-setup` will get called twice, but that shouldn't be an issue. Maybe it's by design.

I mostly use dired for navigation, and only use a handful of the interactive commands. If i need to do something other than open/rename/copy, I usually reach for `M-x` since I can never remember all the keybindings. :)

**Comment by fbergroth** [comment]
Btw, my only annoyance with `dired-x` is that it binds `N`, which is usually bound to `evil-search-previous` (although you can `(setq dired-bind-man nil)`).

**Comment by Ambrevar** [comment]
> then evil-dired-setup will get called twice, but that shouldn't be an issue. Maybe it's by design.

My suggestion of calling it twice was intentional: it's a quick workaround to dired-x overriding some bindings.
The setup function has virtually zero-cost.
Of course we could early-out if we check that dired-x was already loaded, but that's brittle, it increases complexity.  I don't think it's worth it.

**Comment by jojojames** [comment]
In terms of flowchart, putting evil-dired-x in evil-dired will probably look like this?

User triggers 'DIRED' somehow -> evil-dired loads -> with-eval-after-load for dired-x loads -> dired-x loads later -> evil-dired-x bindings load.

Is this palatable if we put dired-x bindings in evil-dired?

**Comment by Ambrevar** [comment]
Not sure I completely got your flowchart, but yes, I think the smarter, more natural way to proceed is to consider dired-x independently (just like image+ even though it's not strictly necessary).

I think it compartimentalize the modes/bindings better.

**Comment by jojojames** [comment]
My flowchart is for the case where evil-dired-x is handled inside the same file as evil-dired.

**Comment by Ambrevar** [comment]
Can you write the loading code explicitely?  It's hard to understand what you mean otherwise.

**Comment by jojojames** [comment]
```
(defun evil-dired-setup ()
  (with-eval-after-load 'dired-x
    ;; some setup happens here
    ))
```

The flowchart is just showing that there's no problem with dired-x being inside evil-dired since it's gated by a with-eval-after-load anyway.

**Comment by Ambrevar** [comment]
That works too: this was my first comment :)

**Comment by jojojames** [comment]
@fbergroth I guess you won't see this problem anymore with the recent changes (removing overriding map from dired so evil's bindings take precedence).

Those dired-x commands seem useful too. If you had some ideas on what to bind them to, that'd be helpful.

**Comment by fbergroth** [comment]
@jojojames Excellent! Of the commands listed above, I only run `dired-omit-mode` in `dired-mode-hook` and occasionally disable the mode manually, so I don't have any good ideas on where to bind them.

**Comment by jojojames** [comment]
Cool, I don't really use the dired-x bindings myself so I don't have a strong opinion here.. If someone else wants to contribute bindings for dired-x, I'll accept a PR.

Otherwise, we can consider this closed.
