### ISSUE TITLE
Rationale: Go To / Toggle / Switch To REPL?

### ISSUE THREAD

**Issue by jojojames** [jojojames/evil-collection#45]
I notice a lot of programming modes have a 'switch'/'start'/etc REPL command.

Would it be unreasonable to put it at something like 'gz'? That's what I've been using so far for it.

**Comment by Ambrevar** [comment]
Sounds reasonable but I almost never use any REPL.  Feel free to add this to the rationale.

**Comment by jojojames** [comment]
Done. https://github.com/jojojames/evil-collection/commit/2a9c7175ba158e0ebdea3e7f4c512342c5b9ba59
