### ISSUE TITLE
Eval when evil-move-beyond-eol is nil

### ISSUE THREAD

**Issue by jojojames** [jojojames/evil-collection#46]
Would be great to have comments for:

https://github.com/jojojames/evil-collection/commit/771dfbea3b1aed7897f0cc15388744500b69777e

https://github.com/jojojames/evil-collection/commit/08cb490f19920e02523aa4182d7b2c40cfe74883

Ideally, I'd like to support evil-move-beyond-eol being nil (since that's the vim default), which means supporting the various lisp modes that eval expecting cursor to be after the last paren.

I'll close this and continue advising those eval functions if there's no comments in a week or two.

**Comment by Ambrevar** [comment]
So strong opinion on this.  I tend to agree with your approach.
