### ISSUE TITLE
"open" bindings: go/gO?

### ISSUE THREAD

**Issue by Ambrevar** [jojojames/evil-collection#47]
Shall we replace the current "gd"/"gD" in the "open" section of the rationale with "go"/"gO"?

I tend to say: yes.

**Comment by jojojames** [comment]
I think we're in agreement.

gd/gD - go to definition related commands
go/gO - open commands

I can already imagine a programming mode can then use something like

gd - go to definition
gD - go to definition (alternative)
go - go to other file (like header / test file)

**Comment by Ambrevar** [comment]
I like your last point!

I currently see that many of your bindings already have "go". (e.g. rtags.)

When we change this, let's make sure that the `;; open` comment is everywhere or else it's hard to track bindings consistently.

**Comment by Ambrevar** [comment]
To sum up:

- `RET` = `go` = open thing at point.
- ` S-RET` = `gO` = open thing at point in other window.
- `M-RET` = view thing at point in other window (keep focus in current window)

Any synonym for `M-RET`?

**Comment by jojojames** [comment]
I think RET is always available so go/gO can be used as more like fallbacks?

RET == RET
go == S-RET
gO == M-RET

But sometims there are no commands that map to S-RET or M-RET.

**Comment by Ambrevar** [comment]
Indeed, then no need for `go`/`gO`.

**Comment by Ambrevar** [comment]
Thinking about this: I believe sorting is far less freaking than opening, so why not exchanging those two `o`/`O` <=> `go`/`gO`?

**Comment by jojojames** [comment]
It's because you can extend the rationale to programming modes where you can do 'go' and not 'o'.

Programming
o - not available (but programming don't have sort keys)
go - available

**Comment by Ambrevar** [comment]
Sure, but if we only consider the case of special modes?  Exchanging `o` and `go` could make sense.
In programming modes, we could use `go` for "opening" anyways.
That would make the rationale a bit more complicated but the bindings more convenient.

What do you think?

**Comment by jojojames** [comment]
Sure, lets try it and see how it goes. (We can always revert if you feel it's awkward later.)

I wanna say we're still (and going to be) in a period where we shouldn't worry about backwards compatibility yet so are free to try these changes out.

**Comment by Ambrevar** [comment]
I've gone for the simple "go"/"gO" only in 1acc818215cdcc50e8086cf648d4544a83f6cb34.
I've added some "TODOs" for your bindings: I think some "o" and "s" can be removed.  You'll be a better judge.

**Comment by jojojames** [comment]
Lets close this for now and re-open if something else crops up.

**Comment by Ambrevar** [comment]
What about rtags, vlf and xref? (The TODOs I mentioned.)
