### ISSUE TITLE
Support evil-search-module set to evil-search

### ISSUE THREAD

**Issue by dieggsy** [jojojames/evil-collection#49]
Here's a (perhaps a bit unclear) similiar issue opened and resolved in evil-magit: https://github.com/emacs-evil/evil-magit/issues/33

tl;dr, when `evil-search-module` is set to `evil-search` (either before evil loads or with custom), different search commands are used, namely `evil-ex-search*` instead of `evil-search*`.

**Comment by jojojames** [comment]
Thanks.

Now the question is whether to hardcode the same logic into every file that needs to explicitly bind / or do *something* else.

https://github.com/emacs-evil/evil-magit/commit/a24186be7cc2cdab24b56f6dcc4665eeb8349c1a

**Comment by noctuid** [comment]
I think all the logic should be in one place. A couple of ways of doing this off the top of my head

- Create variables (e.g. `evil-search-forward`) that hold menu items to conditionally act as one command or the other based on the current value of `evil-search-module`
- Make no changes to the default keybindings; instead, provide a function that takes a keymap as an arg and calls `substitute-key-definition` for all relevant definitions like `evil-select-search-module` does; let the user put it in their setup function

**Comment by dieggsy** [comment]
@noctuid for the second option, couldn't this function be called in elisp when doing `evil-*-setup` ? It could just check `evil-search-module` and make substitutions conditionally.

**Comment by noctuid** [comment]
Yeah, it could do it the same way as evil does it and just automatically check (but still provide the function if the user wants to switch later). I kind of like the the idea of keybindings checking `evil-search-module` each time, but I doubt people toggle `evil-search-module`, so it probably wouldn't be useful.

**Comment by dieggsy** [comment]
In fact, `evil-search-module` needs to be set before evil loads, so toggling it would probably be a pain?

**Comment by noctuid** [comment]
You can use `evil-select-search-module` to change it afterwards. `evil-collection` could do the same thing.

**Comment by jojojames** [comment]
@noctuid I don't have a preference either way here. Which of these is more preferable to you?

@Ambrevar Feel free to chime in too.

**Comment by Ambrevar** [comment]
Hmmm... Stupid question, but what's the difference between the two commands?  I see the point is not moved to the same position during the search, but there must be something else...

If I get the issue correctly (sorry, little time, I just skimmed it), this is the same as for the `C-u` question (in doc-view, image-mode, etc.).
We certainly need a general approach to this, and if it's convincing enough, maybe upstream (Evil) would consider it.

**Comment by noctuid** [comment]
The default uses isearch. Off the top of my head `evil-ex-search` gives you the last search as the default, highlights all candidates in the buffer instead just of the next, doesn't move the point if you abort, and lets you scroll through the history (that may be possible with isearch, I'm not sure). Another difference is that `evil-next-match` (`gn`) only works when the `evil-search-module` is `evil-search`.

**Comment by dieggsy** [comment]
@noctuid @Ambrevar `evil-ex-search` also allows for limited vim-style regex with `evil-ex-search-vim-style-regexp`, which is pretty nice.

**Comment by jojojames** [comment]
Tangential comment, isearch is also way more performant last I checked. I switched back to isearch after slowdowns with evil search.

**Comment by dieggsy** [comment]
@jojojames huh, where were you experiencing slowdowns? just curious. Was it bad enough to warrant a bug to evil? or do you think it's kind of an inevitable limitation

**Comment by jojojames** [comment]
Dunno what it was, large files, the search would just crawl. I just swapped back to isearch for the same search and it went fast again so I attributed it to evil-search. Was a while ago.. Didn't have the energy to create a repro and report it..

**Comment by noctuid** [comment]
It's instant for me in my largest org files (~20k lines). I just tried filling a file with hundreds of thousands of words of lorem ipsum text, and it was still instant even with thousands of matches. That said, I mainly use swiper for searching and set `evil-search-module` primarily so that `evil-next-match` works.

**Comment by jojojames** [comment]
Just tried it again today in an org file (about 6000 lines), it lags on a simple word search.

Swapped back to isearch and it was instant. I noticed a difference was that evil-search seems to highlight matches too. My isearch only highlighted the first match. 

So I do still think there's a performance thing (or at the very least, my setup somehow makes evil-search slower than isearch).

I digress, this would be better off in an evil bug report.

**Comment by jojojames** [comment]
Will take a look a this after the integration stuff is merged in.

> Create variables (e.g. evil-search-forward) that hold menu items to conditionally act as one command or the other based on the current value of evil-search-module

Does it make sense just to use a plain old function that checks that value and calls the right function instead? I'm wondering what the value-add of using the menu-item is over the plain function.

**Comment by noctuid** [comment]
Well, it's more direct and doesn't require a wrapper function. If a user uses `C-h k` it will show the correct command directly, for example. If there are any other cases like this where a menu item could work or is actually necessary, it would also be more consistent to just use menu items and define a macro to make creating them simple.

**Comment by dieggsy** [comment]
agreed with @noctuid about menu items. After using general (and i think yasnippet uses menu items too), it's a much more transparent way to define conditional bindings that doesn't obscure what's happening as much as wrapper functions. I'd rather see `evil-ex-search` or `evil-search` on `C-h k /` than `evil-collection-search` or something like that, which just raises questions. Sure, they're easily avoided by looking at the code, but even more easily avoided (at least on the user side) with menu items IMO.

**Comment by jojojames** [comment]
Thanks, consider me convinced. I'll look into that approach once I find some time.

**Comment by dieggsy** [comment]
Er, on the other hand, checking which module is enabled on init isn't a bad idea, and I think is what evil-magit does (and evil, for that matter). Guess it just doesn't support the toggling search type use-case as stated above, though I think we sorta agree that's gonna be a pretty rare use-case:

> I kind of like the the idea of keybindings checking evil-search-module each time, but I doubt people toggle evil-search-module, so it probably wouldn't be useful.

@noctuid dunno if you stated a preference on checking on init vs menu item. I think I'm sorta fine with both (and the latter covers more ground), just pointing out the former is more consistent with existing behavior

**Comment by jojojames** [comment]
Added something for this @dieggsy !

**Comment by dieggsy** [comment]
Sweet! Thanks!
