### ISSUE TITLE
Init improvements

### ISSUE THREAD

**Issue by Ambrevar** [jojojames/evil-collection#56]
Following up with the comments in 21e9a7d7bc06ec22e2dee5a84deb210485b801b2:

We want:
- defcustoms that will tweak the list of loaded modes in the init function.
- Make the init process and config as straightforward as possible.

Issue:
- As of now, the defcustom has to be set _before_ evil-collection is `require`d.  This can be confusing and should be documented.
- As of now, running the init function after modifying the defcustoms will have no effect.  While this is fine once the setup has been worked out by the user, it's not convenient for experimentating.
- The init function is convoluted.  Adding support for lambdas does not help.

To be honest I'm not completely satisfied with the current state of the init function: it's already convoluted.  Isn't there a simpler approach that would make thinks both straighforward and flexible?  I'll try to come up with one.

**Comment by Ambrevar** [comment]
My main concern is regarding the `evil-collection-setup-minibuffer` defcustom: no code other than the init function _at runtime_ can rely on it since its value is meaningless: it does not carry the information that evil-minibuffer was or will be loaded.
It's confusing.

On the other hand, I tend to agree with @fbergroth, keeping it to the current code is probably simpler, and adding lambdas is unnecessary complexity.
In the end, the mode list is also a defcustom and the user is free to set up whatever.

Isn't it possible to have the defcustom mode list with the minibuffer _disabled_ by default?  That would solve it, no?  Then we can remove the `evil-collection-setup-minibuffer` defcustom.

One way to do it: add `'(minibuffer nil)` to the mode list.
The meaning of it might be confusing though.  A simple comment in the defcustom could clarify.
Or else a constant other than nil, say, `'disabled`.

**Comment by Ambrevar** [comment]
Better, if `custom` supports that: use an alist of all modes with possible values being `nil` (don't load), `t` (load with the key used as name), or a list of symbol (load upon those requirements).

It also makes it easier to check the configuration of a specific mode at any time.

**Comment by Ambrevar** [comment]
I think the info page `(elisp) Composite Types` is precisely what we want.

**Comment by jojojames** [comment]
I do wonder *a little* if we're looking for a solution to a problem we don't have. It's good discussion anyways. :)

As mentioned in the comment thread, if we do any more work to make the init function smarter, we will also take on having to disable/unwinding features which is something it doesn't do right now and might not be feasible.

defcustoms having to be customized using the customize interface is nothing new and having to set the variable up before loading evil-collection isn't a big deal to me.

They could always run the setup function themselves just like before.

Just a quick comment, do note that at some point we'll have to be backwards compatible too.

**Comment by Ambrevar** [comment]
Agreed, we cannot "disable after loading".

But it's not just that: it's about making the code simpler to read and maintain.

Using an alist is much more idiomatic in this case I believe.
We could also completely remove the "type switch" in the init function: that's much leaner in my opinion.

**Comment by jojojames** [comment]
Specifically, what is your worry about the code?

Not that I'm against an alist but the code right now is dead simple already.

**Comment by Ambrevar** [comment]
The following polymorphism can be a little tricky to grasp at first glance:

```
    (let ((m mode)
          (reqs (list mode)))
      (when (listp mode)
        (setq m (car mode)
              reqs (cdr mode)))
```

In my opinion it's good practice to stick to single types.

And the recent minibuffer question shows it's not even that flexible.

I know, it's way too big an issue for such a small detail.  But as you said, let's fix it now before we hit MELPA, backward compatibility is important.

**Comment by jojojames** [comment]
I'm open to opinions here... but that code is fine. I had to look at it recently to figure out what it's doing and grokked it after a minute.

Maybe a more explicit proposal will help. I'm not sure what the value-add of the new proposal (and its tradeoffs) would be without seeing code.

Maybe get an alist branch up and we can compare and contrast.

**Comment by Ambrevar** [comment]
Will do.

**Comment by Ambrevar** [comment]
Check out the `init` branch.

**Comment by fbergroth** [comment]
@Ambrevar: how would you update the readme example?

```
(use-package evil-collection
  :custom (evil-collection-setup-minibuffer t)
  :init (evil-collection-init))
```

**Comment by jojojames** [comment]
@Ambrevar 

So looking at the branch, what is the value-add here that you are seeing?

i.e. How will this help in the future and/or what problems are they solving now.

**Comment by Ambrevar** [comment]
@fbergroth I don't know `use-package`, but I'd assume

```
(use-package evil-collection
  :custom (setcar (alist-get 'minibuffer evil-collection-mode-list) t)
  :init (evil-collection-init))
```

@jojojames: The added value:

- `'minibuffer` can be added before or after `require`ing, does not matter anymore.  That's less room for confusion.
- The `evil-collection-setup-minibuffer` is gone: one defcustom less makes for a simpler config / interface.
- Similarly, all modes can be configured uniformly via the mode list with `customize`.  No need for a defcustom per mode.
- Conversely, we can now uniformly check which mode is activated in the mode list (with a simple `alist-get`).
- `evil-collection-init` is less convoluted.

It's not much, but I don't see any drawback.

**Comment by jojojames** [comment]
At this point, I'm wondering what all the ts are for. To me, the existence of the mode in the list is enough to say we want the mode enabled.

Putting a 't' for every list value seems pretty excessive to me and if we're trying not to be convoluted, we're not doing a good job. :)

I think it might be easier to remove the defcustom for evil-minibuffer and just let the user manually add the 'minibuffer' mode in :init in use-package.

Looking at it more, I do think the code is worse off and more confusing with the alists. Especially for modes like this:

(term t ansi-term multi-term)

You can't even tell how this will eval in the function that uses this list variable. Do we really think this simplifies the code?

I am guessing this will work.

```
(use-package evil-collection
  :init
  (setq evil-collection-mode-list '()) ;; values here
  :config
  (evil-collection-init))

```

**Comment by jojojames** [comment]
> :custom (setcar (alist-get 'minibuffer evil-collection-mode-list) t)

This probably won't work since that :custom is for custom variables. You'd probably need to do this in :init but then why not just modify the list directly instead of this t/nil business.

**Comment by Ambrevar** [comment]
I agree with the `add-to-list` thing, that was my first comment on the matter:
https://github.com/jojojames/evil-collection/commit/21e9a7d7bc06ec22e2dee5a84deb210485b801b2#r26121919

But the whole point of the aforementioned commit is to have a defcustom for minibuffer, disabled by default.

We have two conflicting sides here: those using Lisp to configure (you and me), and those using `customize`
The `t` approach makes more sense in the `custom` interface since a mode is turned on/off with `t`/`nil`.

> You can't even tell how this will eval in the function that uses this list variable.

Sorry, I did not get that.  What do you mean?



Again, I'm fine with an all-Lisp approach with proper comments.
Ultimately, I'd like to get rid of that line which I think is unnecessarily confusing and brittle:
```
,@(when evil-collection-setup-minibuffer '(minibuffer))
```

**Comment by jojojames** [comment]
> I agree with the add-to-list thing, that was my first comment on the matter:
21e9a7d#r26121919

That's my reaction *only* after seeing the proposed changes.

> But the whole point of the aforementioned commit is to have a defcustom for minibuffer, disabled by default.

I still don't have a problem with the defcustom. minibuffer was and still is and is expected to be one of the only special modes
with special handling precisely because it may have confusing behavior. Special casing it with a defcustom is fine to me.

We can have the defcustom before for :custom and add-to-list/push/etc for :init and :config. (Using use-package keywords here to indicate intent.)

> We have two conflicting sides here: those using Lisp to configure (you and me), and those using customize
The t approach makes more sense in the custom interface since a mode is turned on/off with t/nil.

It's excessive is my opinion. We're making this change for one mode (minibuffer) but it affects all the other modes in the list.

> You can't even tell how this will eval in the function that uses this list variable.
Sorry, I did not get that. What do you mean?

One of your goals was code simplicity, adding a random t element in the list structure with trailing elements after is in my opinion
*more* confusing than list splicing.

Just look at the proposed solution now.

```
(setcar (alist-get 'minibuffer evil-collection-mode-list) t)
```

Is that really any easier than (custom-set-variable 'mini-buffer-flag t)?

> Again, I'm fine with an all-Lisp approach with proper comments.
> Ultimately, I'd like to get rid of that line which I think is unnecessarily confusing and brittle:

> ,@(when evil-collection-setup-minibuffer '(minibuffer))

I disagree that this is confusing or brittle. It's a simple list splice and if that's the main motivation for these changes, I don't think we should do it.
Maybe we should discuss why this is perceived to be confusing?

**Comment by Ambrevar** [comment]
>  adding a random t element in the list structure with trailing elements

Maybe that wasn't obvious but the structure I suggested was `(name modes...)`.

> Maybe we should discuss why this is perceived to be confusing?

Hmmm... I should have rephrased "confusing" to "could leave to confusion".

I think all this is because we take two different approaches to programming: I'm inclined to insist on structural integrity, which is what I was trying to do.
My approach is arguably not so "lispish".  Besides, the code is just too short to be complicated and it sounds safe to say that it won't grow larger than it is now.

We've already wasted way to much ink on this nit and I must confess I'm not convinced at all with my own suggestions.

Unless someone wants to chime in, feel free to close.

**Comment by jojojames** [comment]
> My approach is arguably not so "lispish". Besides, the code is just too short to be complicated and it sounds safe to say that it won't grow larger than it is now.

Thanks, sounds like we're in agreement. I'll be good to revisit this if we see a more pressing need in the future though! Lets reopen this issue if you see something else @Ambrevar. :)
