### ISSUE TITLE
Can we make SPC to scroll down optional?

### ISSUE THREAD

**Issue by dieggsy** [jojojames/evil-collection#58]
This might be a bit niche, but I actually use `SPC` as my leader key (I _don't_ use spacemacs, however). If this is a bit too specific, I can got through and unbind in all relevant maps myself.

**Comment by noctuid** [comment]
I think the general solution is to use intercept maps (`evil-make-intercept-map`) for keys you don't want to be overridden and to use a translate function (#5) when you want to keep the functionality but on a different key.

**Comment by dieggsy** [comment]
Well, since I have you here, I currently do this:
```
(general-create-definer
   d/leader-keys
   :states '(emacs normal visual motion insert)
   :non-normal-prefix "C-SPC"
   :prefix "SPC")
```
Would the right way to go about this be the following?:

```
(general-create-definer
   d/leader-keys
   :keymaps 'override
   :states '(emacs normal visual motion insert)
   :non-normal-prefix "C-SPC"
   :prefix "SPC")
```

**Comment by dieggsy** [comment]
Hmm, guess `(general-override-mode)` coupled with the above does what I want. Thanks!

**Comment by jojojames** [comment]
I would've liked to leave SPC open too because SPC is such a common key to use as a 'leader'.

Right now, I'm doing the same thing you're doing @dieggsy.

**Comment by ambihelical** [comment]
@jojojames Just hit this during a rare use of diff-mode.  Could there be something like evil-collection-want-SPC and check that in evil-collection-xxx bindings that currently use SPC or S-SPC (there are roughly 20 or so)  I can add a bug for it, not sure if I have time to do the work.

**Comment by noctuid** [comment]
This has also been discussed in #64. Introducing a variable for this makes things unnecessarily complicated and doesn't solve the bigger issue; any other package can override `SPC` when you don't want it to. You should use intercept maps for keys you don't want overriden.

**Comment by Dickby** [comment]
I think because it's very common to make a custom leader-key in evil-mode, evil-collection should provide an easy way to define a leader-key that evil-collection doesn't override.

**Comment by noctuid** [comment]
There's an example of how to do this in the readme already. See [here](https://github.com/emacs-evil/evil-collection#key-translation). If you use general.el, you can just use the `'override` keymap.

**Comment by ambihelical** [comment]
@noctuid  Thanks, I missed the FAQ entry.  I used the FAQ info, but I didn't set general-override-states, as the default is the same.  So probably that part can be removed?  
I also use the :general extension and don't use hydra for these, so it ends up being as follows (for future visitors):
```
(use-package evil 
 ... other config ....
:general
    (:states '(normal visual emacs) :keymaps 'override
    :prefix "<SPC>"
    ... bindings here ...))
```

**Comment by dieggsy** [comment]
@ambihelical I had also provided a similar example above (in that case with a custom definer, but the logic is the same)
