### ISSUE TITLE
Use `evil-set-initial-state` whenever possible

### ISSUE THREAD

**Issue by Ambrevar** [jojojames/evil-collection#6]
In your "kickstart" file, you've written

  (setq evil-motion-state-modes
        (delete 'ag-mode evil-motion-state-modes)))

I haven't tried but can't we use `evil-set-initial-state`?

Also what is ag-mode and why not being in motion state?

**Comment by jojojames** [comment]
> I haven't tried but can't we use evil-set-initial-state?

Sure, sounds good.

> Also what is ag-mode and why not being in motion state?

It's a wrapper mode around ag (search utility).
There's a package that lets you edit search results in ag and have it reflect in the actual files.
To do this, you'd want to be in normal state and not motion.

wgrep-ag ~

**Comment by Ambrevar** [comment]
OK, then this suggests another point: Add the complete name of the package and optionally the link.

**Comment by jojojames** [comment]
We can close this off with https://github.com/jojojames/evil-collection/commit/387112d892bc3ac41ecffb97771b3176d75d23d2.

Lets revise it in any location that can be using it in the future.

**Comment by Ambrevar** [comment]
What about `occur`?
```
(defun evil-occur-setup ()
  (setq evil-emacs-state-modes
        (remove 'occur-mode evil-emacs-state-modes))
```

**Comment by Ambrevar** [comment]
(I could change this myself but I'd rather wait for your approval since I don't use it much.)

**Comment by jojojames** [comment]
Yeah feel free to change anything. :)

I missed it in my pass through.

**Comment by jojojames** [comment]
https://github.com/jojojames/evil-collection/commit/6129c81ba88afca18ad2bc4ae6d2f973bea9503a
