### ISSUE TITLE
evil-collection not playing nice with ggtags

### ISSUE THREAD

**Issue by hisnawi** [jojojames/evil-collection#67]
I have this configuration for evil-collection and ggtags:

```
  (use-package ggtags
    :ensure t
    :diminish eldoc-mode
    :commands ggtags-mode
    :init
    (add-hook 'asm-mode-hook #'ggtags-mode)
    (add-hook 'c-mode-common-hook
              (lambda ()
                (when (derived-mode-p 'c-mode
                'c++-mode 'java-mode 'asm-mode)
                  (ggtags-mode 1))))
    :config 
    (unbind-key "M-<" ggtags-mode-map)
    (unbind-key "M->" ggtags-mode-map)
    (setq ggtags-mode-line-project-name nil)

    ;; Keys
    (define-key ggtags-mode-map (kbd "C-c g s") 'ggtags-find-other-symbol)
    (define-key ggtags-mode-map (kbd "C-c g h") 'ggtags-view-tag-history)
    (define-key ggtags-mode-map (kbd "C-c g r") 'ggtags-find-reference)
    (define-key ggtags-mode-map (kbd "C-c g f") 'ggtags-find-file)
    (define-key ggtags-mode-map (kbd "C-c g c") 'ggtags-create-tags)
    (define-key ggtags-mode-map (kbd "C-c g u") 'ggtags-update-tags)
    (define-key ggtags-mode-map (kbd "C-c g t") 'ggtags-find-definition)
    (define-key ggtags-mode-map (kbd "M-?")     'ggtags-show-definition)
    (define-key ggtags-mode-map (kbd "M-,")     'pop-tag-mark)
)

 (use-package evil-collection
    :ensure t
    ;;:custom (evil-collection-setup-minibuffer t)
    :init (evil-collection-init))

```
I am using global for tags creation and management, so when using ggtags to jump to definition (M-.) I get a list of "possible" defines in the minibuffer and can jump between then using M-n/p, also jumping back to the original file is done using M-,

Unfortunately, with evil-collection enabled I don't seem to be able to jump between these choices in the mini buffer and when jumping back to the original file the minibuffer doesn't disappear like it used to do.

**Comment by jojojames** [comment]
```
(use-package evil-collection
    :ensure t
    :disabled
    ;;:custom (evil-collection-setup-minibuffer t)
    :init (evil-collection-init))
```
Could you give your exact configuration for this? This paste seems odd.

**Comment by hisnawi** [comment]
Corrected. I just removed the :disabled part.

**Comment by jojojames** [comment]
What about ;;:custom (evil-collection-setup-minibuffer t)?

What are you using for completing-read? Helm/ivy/ido/etc?

**Comment by hisnawi** [comment]
That is the problem, I have both helm and ivy, and enabling evil-collective-setup-minibuffer causes problems and wont be able to select a candidate. So I had to disable it.

**Comment by jojojames** [comment]
Hmnn, I'm still trying to figure out your problem here.

So lets go with a few separate questions.

1. If you enable evil-minibuffer, do you see the problem?

2. If you don't enable evil-minibuffer, do you see the problem?

3. When ggtags is triggered, which completing-read method is used (helm or ivy)?

4. If you *only* call evil-collection-init, do you see the problem?

5. When you're pressing M-,, are you still in the minibuffer?

**Comment by hisnawi** [comment]
1. I don't explicitly no.
2. N/A
3. When ggtags is triggered no completing-read is shown. I was originally referring to finding a tag under point which doesnt require any input.
4. Yes
5. No, I am never in the minibuffer. When jumping to the definition in another file the minibuffer is shown with guessed results but the focus is not in it, and when popping the mark and going back it is still shown but with no focus as well.

I was able to bypass the issue by removing the ggtags from the list of initialization list.

**Comment by jojojames** [comment]
Cool, you might wanna take a look at -> https://github.com/jojojames/evil-collection/blob/master/evil-collection-ggtags.el

to see if there's something we can fix there so you don't have your problem anymore (assuming it is a bug).
