### ISSUE TITLE
Bindings for free-keys

### ISSUE THREAD

**Issue by talwrii** [jojojames/evil-collection#69]
I was setting up some key-bindings for the [freekeys](https://github.com/Fuco1/free-keys), so I thought I would create this here.

Is evil-collection the correct place for this. I wasn't sure if it was intended packages that aren't in emacs core? 

The testing seems to require one add a dependency for `free-keys` if one defines bindings for it... but this doesn't seem like a very friendly thing to do!

**Comment by jojojames** [comment]
Yup, sounds good. Any package that might be wanting evil bindings is fine with me.

> The testing seems to require one add a dependency for free-keys if one defines bindings for it... but this doesn't seem like a very friendly thing to do!

It's your 'require that breaks the tests. We can continue this discussion in your PR. :)

I'll close this, but feel free to reopen if you think there's more we can talk about in this issue.
