### ISSUE TITLE
Swiper evil integration

### ISSUE THREAD

**Issue by YourFin** [jojojames/evil-collection#73]
Hey, I have the following in my [.emacs.d](https://github.com/YourFin/.emacs.d/blob/master/lisp/evil-bindings.el) that makes swiper play nice with evil, most importantly (imo) by having the last swiper search be the default for s commands, so search swiper for "apple" followed by `:s//orange/g` would result in all the apples on the current line being replaced with oranges. The commented out line resets the search direction to forwards, so `n` moves to the further instance down in the file if applicable and `?` is still used for its normal call, but that doesn't seem totally relevant unless you have `/` bound to `swiper` like me.

Relevant code:

    (defun yf--swiper-advice (&rest r)
      (setq isearch-string (substring-no-properties (car swiper-history)))
      ;;(setq isearch-forward t)
      (evil-search-previous))
    (advice-add 'swiper :after #'yf--swiper-advice)

I'm note entirely sure whether or not this would be outside the scope of this package, but I figured it was worth a shot. I'm also happy to put together a PR if someone could give me some direction of where to put it in the filestructure.

**Comment by jojojames** [comment]
Oh this seems pretty cool, the ':s//orange/g' type functionality anyways. I'm not sure what the isearch-forward/evil-search-previous stuff does even after reading your explanation so I'd have to try that advice separately.

As for a PR, you can create a evil-collection-swiper.el file, create a 'setup' function and add the advice under the setup function.

There's a few examples in the package already so it should be safe to copy paste a simple one and modify it to your needs. evil-collection-rjsx-mode is a simple one.

Other than that, it should just byte compile and lint cleanly (the CI will take care of tha though..)

**Comment by dieggsy** [comment]
@YourFin note that swiper does take evil-related pulls (I added a small feature to integrate it with `n` and `N` when `evil-search-module` is `evil-search`.

**Comment by YourFin** [comment]
Swiper pull request at abo-abo/swiper#1406. I'll ditch the other thing I mentioned, it doesn't seem totally relevant or useful.

**Comment by jojojames** [comment]
@YourFin Nice, thanks!
