### ISSUE TITLE
Issues with setting evil-want-integration before evil loads

### ISSUE THREAD

**Issue by hisnawi** [jojojames/evil-collection#76]
This is my setup:

```
  (use-package evil
    :ensure t
    :init
    (setq evil-want-integration nil)
    :config
    (evil-mode)
     .... etc
    )

  (use-package evil-collection
    :after evil
    :ensure t
    :config
    (setq evil-collection-mode-list (remove 'ggtags evil-collection-mode-list))
    (evil-collection-init)
    )

```

I still get a message at startup saying that evil-want-integration is set to nil but not before evil starts!

**Comment by jojojames** [comment]
Is there a chance you have some other packages that require evil before your 'use-package evil' declaration?

**Comment by hisnawi** [comment]
You are correct. I added :after evil to all other packages. Thanks.
