### ISSUE TITLE
Keybinding Syntax

### ISSUE THREAD

**Issue by jojojames** [jojojames/evil-collection#8]
https://github.com/jojojames/evil-integrations/issues/1#issuecomment-341961849

> (14) This is a nit, really, but what about the key binding syntax? I see you use vectors and strings of escape control sequences like "\C-c\C-c". I used to do that, but then some sequence cannot be represented easily, like <backspace>.
I'm now using the following convention: write them like C-h c displays them. It's better for clarity I think, and we want any user to be able to read our bindings. Motto: be as transparent as possible.

    Without modifier not special keys, use a simple string, e.g. "gd".

    Anything else in (kbd ...). Use the <bracket> notation for special keys.

Works for me. We can take care of normalizing this stuff after we've gotten everything into one repo.

**Comment by Ambrevar** [comment]
I took care of it to the extent I could.  Feel free to re-open if something does not work for you.
