### ISSUE TITLE
Suggestion: Add support for reftex

### ISSUE THREAD

**Issue by maxsandova** [jojojames/evil-collection#81]
Reftex's reftex-select-label-mode and reftex-toc-mode-map need some integration, is this kind of packages part of the scope of this package? auctex is a very used packages.

Example: 

```elisp
(evil-define-minor-mode-key 'normal 'reftex-select-label-mode
  "j" 'reftex-select-next
  "k" 'reftex-select-previous 
  "gr" (lambda nil " " (interactive) (throw (quote myexit) 114)) ; does a refresh
  "q" 'reftex-select-quit
 )

(evil-define-minor-mode-key 'normal 'reftex-toc-mode
 "j" 'reftex-toc-next
 "RET" 'reftex-toc-goto-line-and-hide
 "k" 'reftex-toc-previous
 "q" 'reftex-toc-quit
 )
```

**Comment by jojojames** [comment]
Yup, any package that can use evil keybindings is welcome.

A PR is welcome here, I don't use auctex/reftex so wouldn't be able to come up with the bindings for it.

**Comment by maxsandova** [comment]
Ok, I will see what I can do.

**Comment by jojojames** [comment]
Reftex seems handled for now, thanks @maxsandova
