### ISSUE TITLE
Pasting the result of a "yank URL" does not work

### ISSUE THREAD

**Issue by Ambrevar** [jojojames/evil-collection#94]
I've just pushed a change 58d951baea4b8f51191aeca4cc37872f398103fd where I bind "yu" to "yank URL" for EWW, Elfeed and transmission-info.

If works in a sense that I can see the URL in the kill ring.
I cannot paste it with `evil-paste` (`p`) however.  It only moves the cursor forward (?!?).

Any clue why?

**Comment by noctuid** [comment]
In this case `evil-inhibit-operator` needs to be set to `t` to prevent the yank operator's code from running. I left it out for the previous vdiff example because it didn't seem to matter (though maybe it should be added for that as well).

**Comment by noctuid** [comment]
This works correctly for me:
```elisp
(evil-define-key 'operator eww-mode-map
  "u" '(menu-item
        ""
        nil
        :filter (lambda (&optional _)
                  (setq evil-inhibit-operator t)
                  (when (memq evil-this-operator
                              evil-collection-yank-operators)
                    #'eww-copy-page-url))))
```

**Comment by Ambrevar** [comment]
That did it, thanks @noctuid!
